name: Build a Package
on:
  workflow_dispatch:
    inputs:
      bazelBuildArgs:
        type: string
        description: A value for `--bazel_build_opts`
      windowsBuildArgs:
        type: string
        description: Build options for Windows Build
jobs:
  package:
    uses: ./.github/workflows/package.yml
    with:
      ref: ${{ github.event.ref }}
      packageName: package
      bazelBuildArgs: ${{ inputs.bazelBuildArgs || '--experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0' }}
      windowsBuildArgs: ${{ inputs.windowsBuildArgs || '--desktop cpu --opencv cmake' }}
    secrets: inherit
