name: Build a nuget
on:
  workflow_dispatch:
    inputs:
      nugetPushArgs:
        type: string
        description: A value for `--bazel_build_opts`
jobs:
  package:
    uses: ./.github/workflows/nuget.yml
    with:
      ref: ${{ github.event.ref }}
      packageName: nuget
      nugetPushArgs: ${{ inputs.nugetPushArgs || '' }}
    secrets: inherit
